# -*- coding: utf-8 -*-
"""Ayush-ngk-LP-1-graph.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zqXmPRmGaYrRrD8ueJi_u51yGJAHX-vX
"""

import networkx as nx
import matplotlib.pyplot as plt
  
G = nx.Graph()
G.add_edges_from([(1, 2), (1, 3), (1, 4), (3, 4), (4, 5)])
  
plt.figure(figsize =(10, 10))
nx.draw_networkx(G, with_labels = True)

print("Triadic closure below :")
e = list(G.edges())